# DETR模型配置文件 - 实例分割版本

# 任务和模型类型
task:
  type: instance  # 任务类型：instance
  model_type: detr  # 模型类型：detr

# 模型架构参数
model:
  name: detr
  backbone_type: resnet18  # 主干网络类型
  num_classes: 20  # VOC数据集类别数（不包括背景类）
  hidden_dim: 256
  nhead: 4
  num_encoder_layers: 3
  num_decoder_layers: 3
  dim_feedforward: 1024
  dropout: 0.2
  num_queries: 20  # 每张图片最多预测20个实例（VOC数据集中通常每张图片包含1-10个实例）
  activation: relu

# 训练超参数
train:
  epochs: 50
  batch_size: 2
  num_workers: 4
  learning_rate: 1.0e-4
  weight_decay: 1.0e-4
  lr_drop: 200
  clip_max_norm: 0.1

# 优化器设置
optimizer:
  type: AdamW
  backbone_lr: 1.0e-5
  backbone_weight_decay: 1.0e-4

# 数据集配置
dataset:
  name: voc
  root: datasets/VOC2012
  size: [512, 512]  # 添加输入尺寸配置
  transform:
    train:
      random_resize:
        min_size: 280
        max_size: 400
      random_rotation:
        degrees: 10
        expand: true
      random_scale:
        min_scale: 0.8
        max_scale: 1.2
      random_crop:
        size: [512, 512]
      horizontal_flip:
        p: 0.5
      color_jitter:
        brightness: 0.2
        contrast: 0.2
        saturation: 0.2
      resize:
        size: [512, 512]
      normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    val:
      resize:
        size: [512, 512]
      normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

# 损失函数权重
loss:
  ce: 2.0    # 分类损失权重
  mask: 200.0  # 掩码损失权重
  dice: 5.0  # Dice损失权重
  eos_coef: 0.05  # 背景类权重系数

# 保存设置
save:
  checkpoint_dir: checkpoints/instance/detr  # 实例分割模型保存路径
  save_freq: 10  # 每隔多少轮保存一次
  save_best: true  # 是否保存最佳模型
  metric: mAP  # 用于选择最佳模型的指标（实例分割使用mAP）