# UNet模型配置文件

# 任务和模型类型
task:
  type: semantic  # 任务类型：semantic 或 instance
  model_type: unet  # 模型类型：detr, unet, saunet, cnn

# 模型架构参数
model:
  name: unet
  n_channels: 3  # 输入通道数
  n_classes: 21  # VOC数据集类别数（包括背景）
  bilinear: true  # 是否使用双线性插值上采样

# 训练超参数
train:
  epochs: 50
  batch_size: 8
  num_workers: 8
  learning_rate: 1.0e-4
  weight_decay: 1.0e-4
  lr_scheduler:
    type: StepLR
    step_size: 30
    gamma: 0.1

# 优化器设置
optimizer:
  type: Adam
  betas: [0.9, 0.999]
  eps: 1.0e-8

# 数据集配置
dataset:
  name: voc  # 数据集名称
  root: datasets/VOC2012  # 数据集根目录
  size: [512, 512]  # 图像尺寸
  transform:
    train:
      - name: RandomResize
        min_size: 512
        max_size: 512
      - name: RandomHorizontalFlip
        prob: 0.5
      - name: ToTensor
      - name: Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    val:
      - name: Resize
        size: 512
      - name: ToTensor
      - name: Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

# 损失函数设置
loss:
  type: CrossEntropyLoss  # 使用交叉熵损失
  ignore_index: 255  # 忽略的标签值

# 评估指标
metrics:
  # 分割质量相关指标
  - name: mIoU  # 平均交并比
  - name: pixel_accuracy  # 像素准确率
  - name: mean_accuracy  # 平均准确率
  - name: frequency_weighted_iou  # 频率加权IoU

# 保存设置
save:
  checkpoint_dir: checkpoints/semantic/unet  # 更新保存路径以反映任务类型
  save_freq: 10  # 每隔多少轮保存一次
  save_best: true  # 是否保存最佳模型
  metric: mIoU  # 用于选择最佳模型的指标